name: Notificar responsável pelo Pull Request

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Comentar no PR mencionando responsável
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const assignees = (pr.assignees || []).map(a => a.login);
            const toMention = assignees.length ? assignees : [pr.user.login];
            const body = `@${toMention.join(', @')} favor verificar este Pull Request (#${pr.number}). Obrigado!`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body
            });
